import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SideBar from "../components/widgets/SideBar";
import VirtualTour from "../components/landing/VirtualTour";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-5 pb-0 mb-0">
        <SideBar />

        <VirtualTour />
      </div>
    </div>
  );
};

export default Home;
